
title: Anom's Resume
url: 'https://sir-croki.github.io/online-cv'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Anom Yulian Hartanto
tagline: Frontend Developer
pic: anom-circle.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: a.yulian.h@gmail.com
phone: 0812 2013 808
linkedin: anom-yulian
github: sir-croki

#Update all the sections by editing the files inside _includes folder.
